name = "lavender-house-cleaning-api"
main = "src/index.js"
compatibility_date = "2026-08-27"
compatibility_flags = ["nodejs_compat"]
account_id = "98097e6545c460df74e29e2025c5d5b7"

[[d1_databases]]
binding = "DB"
database_name = "lavender-house-cleaning-db"
database_id = "5abe58c4-881b-428a-9fdf-ef6766aa0e8d"

[vars]
CORS_ORIGIN = "https://www.lavenderhousecleaning.company,https://lavenderhousecleaning.company,https://lavender-house-cleaning.pages.dev"
